# Generated by Django 3.0.5 on 2020-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jorang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='16진수 코드 6개 ex) FFFFFF', max_length=6)),
            ],
        ),
    ]
