# Generated by Django 3.0.5 on 2020-12-26 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pushnotificationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseUID',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='유저 UID (Firebase 에서 자동 생성)')),
            ],
        ),
    ]
