# Generated by Django 3.0.5 on 2020-12-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_firebaseuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jorang',
        ),
    ]
