# Generated by Django 3.0.5 on 2020-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usercoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
