# Generated by Django 3.0.5 on 2020-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercoin_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorang',
            name='status',
            field=models.CharField(choices=[('0', '알'), ('1', '유년기'), ('2', '성장기'), ('3', '성숙기')], default=0, max_length=2),
        ),
    ]
