# Generated by Django 3.0.5 on 2021-01-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210104_1702'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO shop_jorang (
                id,
                profile_id,
                nickname,
                color,
                status,
                title
            )
            SELECT
                id,
                profile_id,
                nickname,
                color,
                status,
                title
            FROM
                core_jorang
            """, reverse_sql="""
            INSERT INTO core_jorang (
                id,
                profile_id,
                nickname,
                color,
                status,
                title
            )
            SELECT
                id,
                profile_id,
                nickname,
                color,
                status,
                title
            FROM
                shop_jorang
            """
        )
    ]
