# Generated by Django 3.0.5 on 2020-07-10 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jorang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorang',
            name='title',
            field=models.CharField(default='Da:haeng', max_length=100),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emotion', models.CharField(max_length=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
