# Generated by Django 3.0.5 on 2020-07-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200710_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorang',
            name='title',
            field=models.CharField(default='Da:haeng', max_length=100),
        ),
    ]
