# Generated by Django 3.0.5 on 2020-07-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jorang_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='emotion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
