# Generated by Django 3.0.5 on 2020-07-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attendance_emotion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('profile', 'date')},
        ),
    ]
