# Generated by Django 3.0.5 on 2020-06-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
        ('reminder', '0003_reminder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Post'),
        ),
    ]
