# Generated by Django 3.0.5 on 2020-07-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20200602_1830'),
        ('reminder', '0005_auto_20200605_1845'),
    ]

    operations = [
    ]
