# Generated by Django 3.0.5 on 2020-07-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('item_detail', models.CharField(max_length=100)),
                ('item_price', models.PositiveIntegerField()),
                ('released_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-released_at'],
                'unique_together': {('item_type', 'item_detail')},
            },
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_worn', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Items')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile', 'item')},
            },
        ),
    ]
