# Generated by Django 3.0.5 on 2021-01-03 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jorang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', '알'), ('1', '유년기'), ('2', '성장기')], default=0, max_length=2)),
                ('title', models.CharField(default='Da:haeng', max_length=100)),
                ('items', models.ManyToManyField(to='shop.UserItem')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
