# Generated by Django 3.0.5 on 2021-01-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210104_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jorang',
            name='color',
        ),
    ]
