# Generated by Django 3.0.5 on 2021-01-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_jorang_color'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO shop_useritem(profile_id, item_id, is_worn)
            SELECT core_profile.id, shop_item.id, True
            FROM core_profile, shop_item
            WHERE shop_item.item_detail = "background-ground"
            AND shop_item.item_type = "background"
            """
        )
    ]
