# Generated by Django 3.0.5 on 2021-01-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210110_1809'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO shop_jorang_items(useritem_id, jorang_id)
            SELECT shop_useritem.id, shop_jorang.id
            FROM shop_jorang, shop_item, shop_useritem
            WHERE shop_jorang.profile_id = shop_useritem.profile_id
            AND shop_useritem.item_id = shop_item.id
            AND shop_item.item_detail = "background-ground"
            """
        )
    ]
