# Generated by Django 3.0.5 on 2020-06-02 09:30

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image_sample.jpg', upload_to=record.models.date_upload_to),
        ),
    ]
