# Generated by Django 3.0.5 on 2020-07-24 05:00

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=record.models.date_upload_to),
        ),
    ]
