# Generated by Django 3.0.5 on 2020-06-05 16:47

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200605_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image_sample.jpg', null=True, upload_to=record.models.date_upload_to),
        ),
    ]
