# Generated by Django 3.0.5 on 2020-06-20 13:33

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200606_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continuity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image_sample.jpg', upload_to=record.models.date_upload_to),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
