# Generated by Django 3.0.5 on 2020-07-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_post_image'),
        ('record', '0005_auto_20200706_1905'),
    ]

    operations = [
    ]
